---
- name: Import job
  jenkins_job:
    config: "{{ lookup('template', 'templates/job.xml') }}"
    name: "{{ item.name }}"
    password: admin
    url: http://localhost:8080
    user: admin
  with_items: "{{ jenkins_jobs }}"
