# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "webserver" do |server|
    server.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "jenkins" do |server|
    server.vm.network "private_network", ip: "192.168.33.11"
    server.vm.network "forwarded_port", guest: 8080, host: 8080
  end

  config.vm.define "prometheus" do |server|
    server.vm.network "private_network", ip: "192.168.33.12"
    server.vm.network "forwarded_port", guest: 9090, host: 9090
  end

end
