# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "webserver" do |server|
    server.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "jenkins" do |server|
    server.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "prometheus" do |server|
    server.vm.network "private_network", ip: "192.168.33.12"
  end

end
